// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
)

type Deliveryman struct {
	ID           uuid.UUID
	Name         string
	Age          int32
	AddressState string
	AddressCity  string
}
